apiVersion: constraints.gatekeeper.sh/v1beta1
kind: RohanRequiredLabels
metadata:
  name: pod-must-have-lable
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]   
  parameters:
    labels: ["app"]
